### ISSUE TITLE
Unable to download anymore - "This repository is over its data quota"

### ISSUE THREAD

**Issue by srhrshr** [mmihaltz/word2vec-GoogleNews-vectors#2]
I get the following message on doing `git lfs clone` :
```
batch response: http: This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/
```

**Comment by AwasthiMaddy** [comment]
See the issue 1 of this repository. Another link is there to download the google news word vectors.

**Comment by srhrshr** [comment]
Thanks. I actually used gdown.pl and downloaded it from the drive directly. I think we should update the readme with the s3 link in [issue 1](https://github.com/mmihaltz/word2vec-GoogleNews-vectors/issues/1). I'll send a PR.
